version: '3.8'

x-common-variables: &common-variables
  PORT_UI: '3000'
  PORT_API: '3001'

services:
  # mysql_db:
  #   image: mysql
  #   restart: always
  #   cap_add:
  #     - SYS_NICE
  #   volumes:
  #     - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
  #   ports:
  #     - "9906:3306"
  #   environment:
  #     <<: *common-variables
  #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
  #     MYSQL_HOST: localhost

  nginx:
    depends_on:
      - api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile.nginx
      context: ./
    ports:
      - "3050:80"

  api:
    environment:
      <<: *common-variables
      # MYSQL_HOST_IP: mysql_db
    build:
      dockerfile: Dockerfile.api
      context: ./
    # volumes:
    #   - /app/node_modules
    #   - ./projects/api:/app

  ui:
    stdin_open: true
    environment:
      <<: *common-variables
    build:
      dockerfile: Dockerfile.ui
      context: ./
    # volumes:
    #   - /app/node_modules
    #   - ./projects/ui:/app
